// flow-typed signature: 7e91689e234c4451e899a1714d71395b
// flow-typed version: <<STUB>>/realm_v^0.15.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'realm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'realm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'realm/lib/browser/base64' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/collections' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/constants' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/index' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/lists' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/objects' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/results' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/rpc' {
  declare module.exports: any;
}

declare module 'realm/lib/browser/util' {
  declare module.exports: any;
}

declare module 'realm/lib/collection-methods' {
  declare module.exports: any;
}

declare module 'realm/lib/errors' {
  declare module.exports: any;
}

declare module 'realm/lib/extensions' {
  declare module.exports: any;
}

declare module 'realm/lib/index' {
  declare module.exports: any;
}

declare module 'realm/lib/user-methods' {
  declare module.exports: any;
}

declare module 'realm/react-native/index' {
  declare module.exports: any;
}

declare module 'realm/react-native/listview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'realm/lib/browser/base64.js' {
  declare module.exports: $Exports<'realm/lib/browser/base64'>;
}
declare module 'realm/lib/browser/collections.js' {
  declare module.exports: $Exports<'realm/lib/browser/collections'>;
}
declare module 'realm/lib/browser/constants.js' {
  declare module.exports: $Exports<'realm/lib/browser/constants'>;
}
declare module 'realm/lib/browser/index.js' {
  declare module.exports: $Exports<'realm/lib/browser/index'>;
}
declare module 'realm/lib/browser/lists.js' {
  declare module.exports: $Exports<'realm/lib/browser/lists'>;
}
declare module 'realm/lib/browser/objects.js' {
  declare module.exports: $Exports<'realm/lib/browser/objects'>;
}
declare module 'realm/lib/browser/results.js' {
  declare module.exports: $Exports<'realm/lib/browser/results'>;
}
declare module 'realm/lib/browser/rpc.js' {
  declare module.exports: $Exports<'realm/lib/browser/rpc'>;
}
declare module 'realm/lib/browser/util.js' {
  declare module.exports: $Exports<'realm/lib/browser/util'>;
}
declare module 'realm/lib/collection-methods.js' {
  declare module.exports: $Exports<'realm/lib/collection-methods'>;
}
declare module 'realm/lib/errors.js' {
  declare module.exports: $Exports<'realm/lib/errors'>;
}
declare module 'realm/lib/extensions.js' {
  declare module.exports: $Exports<'realm/lib/extensions'>;
}
declare module 'realm/lib/index.js' {
  declare module.exports: $Exports<'realm/lib/index'>;
}
declare module 'realm/lib/user-methods.js' {
  declare module.exports: $Exports<'realm/lib/user-methods'>;
}
declare module 'realm/react-native/index.js' {
  declare module.exports: $Exports<'realm/react-native/index'>;
}
declare module 'realm/react-native/listview.js' {
  declare module.exports: $Exports<'realm/react-native/listview'>;
}
