// flow-typed signature: 9162753d84808ed381a4e50409e4e0b7
// flow-typed version: <<STUB>>/redux-analytics_v^0.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-analytics/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'redux-analytics/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'redux-analytics/lib/index' {
  declare module.exports: any;
}

declare module 'redux-analytics/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-analytics/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'redux-analytics/coverage/lcov-report/prettify'>;
}
declare module 'redux-analytics/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'redux-analytics/coverage/lcov-report/sorter'>;
}
declare module 'redux-analytics/lib/index.js' {
  declare module.exports: $Exports<'redux-analytics/lib/index'>;
}
declare module 'redux-analytics/test/index.js' {
  declare module.exports: $Exports<'redux-analytics/test/index'>;
}
